[build]
  command = "npm run build"
  publish = ".next"
  
[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
  cloudName = "cloudinary://881277729972594:2dbUumKSd3Trzc-Du8GspO0FhNw@dgjtact77"

